### ISSUE TITLE
Date range selector not rendering selection when using format props

### ISSUE THREAD

**Issue by zwenza** [MarceloPrado/flash-calendar#69]
### Example

Expo snack for reproduce able example: https://snack.expo.dev/@djoech/flash-calendar-format-bug

### Description 
Not sure if I am using the library wrong in some way or if it is an actual bug, however I can reproduce it in the snack.

I am saving a date-range selection into my context to share it across views. However once I start using `<Calendar />` with a pre-selected date range `useDateRange({ startId, endId })` the range will not be rendered correctly when I use any format props like  `getCalendarDayFormat`, `getCalendarMonthFormat` or `getCalendarWeekDayFormat`.

It renders correct if I use both without the other one, but together the bug occurs. 
The date range flickers and then proceeds to not be rendered.

### Example Code

```tsx
import { Text, SafeAreaView, StyleSheet } from 'react-native';
import { Calendar, toDateId, useDateRange } from "@marceloterreiro/flash-calendar";
import { format } from 'date-fns'
import { useState, useEffect } from "react";

const today = toDateId(new Date());

export default function App() {
  // This state is simplified for the example. In my case it would come from a context.
  const [start, setStart] = useState(today);
  const [end, setEnd] = useState(today);

  const {
    onCalendarDayPress,
    isDateRangeValid,
    calendarActiveDateRanges,
  } = useDateRange({ startId: start, endId: end }); // I am setting the default range here because I want the data from my context to be pre-selected here

  useEffect(() => {
    // Every time the selected range changed I want to update my context (in this example the state)
    if (isDateRangeValid && calendarActiveDateRanges.length > 0) {
      const range = calendarActiveDateRanges[0];
      setStart(range.startId)
      setEnd(range.endId)
    }
  }, [calendarActiveDateRanges, isDateRangeValid]);

  return (
    <SafeAreaView>
      <Calendar
        // Any format function causes the range picker to not render correct after completing a selection
        getCalendarWeekDayFormat={
          date => format(date, "EEEEEE")
        }
        calendarColorScheme="light"
        calendarMonthId={today}
        calendarFirstDayOfWeek="monday"
        calendarActiveDateRanges={calendarActiveDateRanges}
        onCalendarDayPress={onCalendarDayPress}
      />
    </SafeAreaView>
  );
}
```

Let me know if I can help in some way!

**Comment by MarceloPrado** [comment]
Hi @zwenza, thanks for reporting it, and for providing the code to repro. I was able to investigate and understand the problem. Turns out it's being caused by the arrow function, which breaks referential equality:

https://github.com/user-attachments/assets/aae8f795-6611-46d0-841b-8fd6e20a089b

The reason this happens is due to the mechanism used by Flash Calendar to avoid re-rendering days unaffected by the selected range. Instead of a plain-old React state, I'm using an [event-emitter to publish the range](https://github.com/marceloprado/flash-calendar/blob/3e07dd96e6ca242b95abc0e1453609e7309849a4/packages/flash-calendar/src/components/Calendar.tsx#L189-L192), and only the relevant days [consume this event](https://github.com/marceloprado/flash-calendar/blob/3e07dd96e6ca242b95abc0e1453609e7309849a4/packages/flash-calendar/src/hooks/useOptimizedDayMetadata.ts#L55-L90).

### Why does referential equality matter?
When you use an arrow function for the date formatting, you break referential equality, and React thinks your Calendar updated. This causes [`BaseCalendar`](https://github.com/marceloprado/flash-calendar/blob/3e07dd96e6ca242b95abc0e1453609e7309849a4/packages/flash-calendar/src/components/Calendar.tsx#L100-L178) to re-render, and by consequence, the CalendarItemDay component. 

Once CalendarItemDay re-renders, [this line](https://github.com/marceloprado/flash-calendar/blob/3e07dd96e6ca242b95abc0e1453609e7309849a4/packages/flash-calendar/src/hooks/useOptimizedDayMetadata.ts#L50-L53) gets called, and resets the date range. **It would require the event to be re-published**.

Even though `BaseCalendar` re-rendered, the top-level component (`Calendar`) is stable, and does not re-render. This means the event [does not get re-published](https://github.com/marceloprado/flash-calendar/blob/3e07dd96e6ca242b95abc0e1453609e7309849a4/packages/flash-calendar/src/components/Calendar.tsx#L188-L203).

You don't have to understand this part though, I'm only explaining in case you're curious. Avoiding re-renders was one of the most challenging pieces of Flash Calendar, and required this unconventional pub/sub approach 🙂. 

I added some light docs on this here: #72

Let me know if it solves your problem!

**Comment by zwenza** [comment]
Thank you very much for the explanation @MarceloPrado this makes perfectly sense! 
And great addition to the docs in case someone stumbles over the same problem 👍
